#!/usr/bin/env bash
# agent_env_test.sh — tools/agent-env.sh, which puts the sibling toolchain on
# PATH for agent shells.
#
# Every case here is a bug that shipped. This tool runs from a PreToolUse hook
# on every shell command an agent issues, so its failure modes are silent and
# total: a shell that exits, a PATH that grows without bound, a cache emptied
# at the one moment it was needed.
. "$(dirname "$0")/helpers.sh"

ws="$(make_workspace)"
collection="$ws/demo"
mkdir -p "$collection"
cp -R "$ws/main/harness" "$collection/harness"
agent_env="$collection/harness/tools/agent-env.sh"

# A toolchain prefix that exists on disk but is nothing like a real PATH, so
# an assertion cannot pass by accident on the developer's own environment.
fake_bin="$(mktemp_dir bins)"
mkdir -p "$fake_bin/alpha" "$fake_bin/beta"
prefix="$fake_bin/alpha:$fake_bin/beta"

write_cache() { # seed .env.toolchain directly; mise may not be installed here
  cat > "$collection/.env.toolchain" <<EOF
# Generated by harness/tools/agent-env.sh — machine-local toolchain bins.
WTC_TOOLCHAIN_PATH=$prefix
EOF
}
write_cache

# Run agent-env.sh with a controlled environment: no mise, a known PATH, and
# the collection named explicitly so it never walks up into a real workspace.
in_clean_shell() { # <bash -c script>
  env -i HOME="$HOME" PATH=/usr/bin:/bin \
      CLAUDE_PROJECT_DIR="$collection" \
      /bin/bash -c "$1"
}

# --- sourced mode must not kill the calling shell ---------------------------
# The header advertises `. agent-env.sh` and BASH_ENV. A trailing `exit 0`
# made both take the *calling* shell down: the shell simply stopped, with no
# error, so under BASH_ENV every command in the session became a silent no-op.

it "sourcing it leaves the shell alive"
out="$(in_clean_shell ". '$agent_env'; echo STILL_ALIVE")"
assert_eq "STILL_ALIVE" "$out"

it "sourcing it applies the prefix to the calling shell"
out="$(in_clean_shell ". '$agent_env'; echo \"\$PATH\"")"
assert_contains "$out" "$fake_bin/alpha"
out="$(in_clean_shell ". '$agent_env'; echo \"\${WTC_AGENT_ENV:-unset}\"")"
assert_eq "1" "$out"

it "sourcing it is silent on stdout and stderr"
# Anything printed here lands in the middle of whatever the shell was doing,
# and under BASH_ENV that is every command.
out="$(in_clean_shell ". '$agent_env' 2>&1 >/dev/null; :" 2>&1)"
assert_empty "$out"

it "BASH_ENV applies it to a non-interactive shell"
# This is the case agent CLIs actually produce, and the reason the sourced
# mode exists at all.
out="$(env -i HOME="$HOME" PATH=/usr/bin:/bin \
      CLAUDE_PROJECT_DIR="$collection" BASH_ENV="$agent_env" \
      /bin/bash -c 'echo "$PATH"')"
assert_contains "$out" "$fake_bin/alpha"

# --- PATH hygiene -----------------------------------------------------------

it "eval-ing it repeatedly does not grow PATH"
# `.envrc`, the herdr workspace env and the PreToolUse hook can all apply the
# same prefix to one shell. Without a guard each eval prepends another copy.
script="eval \"\$(bash '$agent_env')\"; a=\$(echo \"\$PATH\" | tr : '\n' | wc -l)
eval \"\$(bash '$agent_env')\"; eval \"\$(bash '$agent_env')\"
b=\$(echo \"\$PATH\" | tr : '\n' | wc -l)
echo \"\$a \$b\""
set -- $(in_clean_shell "$script")
assert_eq "$1" "$2" "PATH length after 1 eval vs 3"

it "an empty PATH gains no empty element"
# An empty element in PATH means the current directory. In something that runs
# on every tool call that is a footgun, not a nit.
out="$(env -i HOME="$HOME" CLAUDE_PROJECT_DIR="$collection" \
      /bin/bash -c "unset PATH; eval \"\$(/bin/bash '$agent_env')\"; echo \":\$PATH:\"")"
assert_not_contains "$out" "::"

# --- the cache --------------------------------------------------------------

it "--write keeps a good cache when mise is missing"
# The SessionStart hook is exactly the place likely to run in a shell too bare
# to find mise. Writing an empty WTC_TOOLCHAIN_PATH there reintroduces the bug
# the tool exists to fix, at the moment the cache matters most.
write_cache
before="$(cat "$collection/.env.toolchain")"
in_clean_shell "'$agent_env' --write"
after="$(cat "$collection/.env.toolchain")"
assert_eq "$before" "$after" "cache survives a mise-less --write"

it "--print-path reads the cache back"
out="$(in_clean_shell "'$agent_env' --print-path")"
assert_eq "$prefix" "$out"

# --- the PreToolUse wrapper -------------------------------------------------

it "--wrap rewrites a command to apply the prefix first"
out="$(printf '{"tool_input":{"command":"echo hi"}}' | in_clean_shell "'$agent_env' --wrap")"
assert_contains "$out" "updatedInput"
assert_contains "$out" "wtc-agent-env"

it "--wrap is idempotent on an already-wrapped command"
already='{"tool_input":{"command":"# wtc-agent-env\neval x\necho hi"}}'
out="$(printf '%s' "$already" | in_clean_shell "'$agent_env' --wrap")"
assert_empty "$out" "no second wrap"

it "--wrap no-ops on input it cannot use"
for payload in '' 'not json at all' '{}' '{"tool_input":{}}' '{"tool_input":{"command":""}}'; do
  out="$(printf '%s' "$payload" | in_clean_shell "'$agent_env' --wrap")"
  assert_empty "$out" "no rewrite for: ${payload:-<empty>}"
done

it "--wrap exits 0 even when it declines to rewrite"
# A nonzero exit from a PreToolUse hook can block the tool call it was meant
# to help.
assert_ok sh -c "printf 'garbage' | env -i HOME='$HOME' PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR='$collection' /bin/bash '$agent_env' --wrap"

# --- fail-open --------------------------------------------------------------

it "it exits 0 outside any collection"
nowhere="$(mktemp_dir nowhere)"
assert_ok env -i HOME="$HOME" PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR="$nowhere" \
  /bin/bash "$agent_env" --write

it "sourcing it outside any collection still leaves the shell alive"
# The other half of the `exit` bug: the early "no collection here" return was
# also an exit, so a BASH_ENV pointed at a retired collection killed the shell.
out="$(env -i HOME="$HOME" PATH=/usr/bin:/bin CLAUDE_PROJECT_DIR="$nowhere" \
      /bin/bash -c ". '$agent_env'; echo STILL_ALIVE")"
assert_eq "STILL_ALIVE" "$out"
